import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const exercisesData = [
  {
    exerciseId: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    aliases: ['DB Bench'],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['dumbbell', 'bench'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['PRIMARY', 'ASSISTANCE'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'More ROM and unilateral stability vs barbell.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs, focus on tempo.', typicalReps: '3 x 10–15' },
      { tier: 'GOLD', description: 'Moderate DBs, strength focus.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Heavy DBs or slight incline.', typicalReps: '4–5 x 6–8' },
    ],
  },
  {
    exerciseId: 'db_incline_bench',
    name: 'Incline Dumbbell Bench Press',
    aliases: ['Incline DB Bench'],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['upper_chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['dumbbell', 'bench'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE'],
    suitableArchetypes: ['FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Targets upper chest and shoulders.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs.', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Heavy DBs.', typicalReps: '4 x 6–8' },
    ],
  },
  {
    exerciseId: 'db_floor_press',
    name: 'Dumbbell Floor Press',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'PRIMARY'],
    suitableArchetypes: ['PR1ME', 'FORGE'],
    indoorFriendly: true,
    notes: 'Great for shoulders; limited ROM.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs.', typicalReps: '3 x 12–15' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Heavy DBs.', typicalReps: '4 x 6–8' },
    ],
  },
  {
    exerciseId: 'db_row',
    name: 'Single-Arm Dumbbell Row',
    aliases: ['DB Row'],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['lats', 'mid_back'],
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell', 'bench'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE'],
    suitableArchetypes: ['FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Unilateral back builder; easy for all levels.',
    tiers: [
      { tier: 'SILVER', description: 'Light DB, controlled.', typicalReps: '3 x 12 each' },
      { tier: 'GOLD', description: 'Moderate load.', typicalReps: '4 x 8–10 each' },
      { tier: 'BLACK', description: 'Heavy DB in EMOM or superset.', typicalReps: '4 x 6–8 each' },
    ],
  },
  {
    exerciseId: 'db_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['lateral_delts'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'FINISHER'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Shoulder isolation; great pump work.',
    tiers: [
      { tier: 'SILVER', description: 'Very light DBs.', typicalReps: '3 x 15–20' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '3–4 x 10–15' },
      { tier: 'BLACK', description: 'Heavier with partials or drop sets.', typicalReps: '4 x 12–20' },
    ],
  },
  {
    exerciseId: 'db_bicep_curl',
    name: 'Dumbbell Biceps Curl',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'FINISHER'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Simple arm work; good for supersets.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs.', typicalReps: '3 x 12–15' },
      { tier: 'GOLD', description: 'Moderate load.', typicalReps: '3–4 x 8–12' },
      { tier: 'BLACK', description: 'Heavier or tempo curls.', typicalReps: '4 x 8–10' },
    ],
  },
  {
    exerciseId: 'db_tricep_extension',
    name: 'Dumbbell Triceps Extension',
    aliases: ['Overhead Triceps Extension'],
    category: 'STRENGTH',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'FINISHER'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Lockout strength; single or two-hand.',
    tiers: [
      { tier: 'SILVER', description: 'Light DB, seated.', typicalReps: '3 x 12–15' },
      { tier: 'GOLD', description: 'Moderate load.', typicalReps: '3–4 x 10–12' },
      { tier: 'BLACK', description: 'Heavier, higher volume.', typicalReps: '4 x 8–10' },
    ],
  },
  {
    exerciseId: 'db_step_up',
    name: 'Dumbbell Step-Up',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['dumbbell', 'plyo_box'],
    space: 'OPEN_AREA',
    impactLevel: 'MEDIUM',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['FORGE', 'ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Unilateral leg strength and balance.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight or low box.', typicalReps: '3 x 8–10 each' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 10–12 steps' },
      { tier: 'BLACK', description: 'Heavier DBs or higher box.', typicalReps: '4 x 12–15 steps' },
    ],
  },
  {
    exerciseId: 'db_rev_lunge',
    name: 'Dumbbell Reverse Lunge',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['dumbbell'],
    space: 'LANE_5M',
    impactLevel: 'MEDIUM',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Knee friendly unilateral pattern.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight reverse lunges.', typicalReps: '3 x 8–10 each' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 8–12 each' },
      { tier: 'BLACK', description: 'Heavier DBs or front rack.', typicalReps: '4 x 10–12 each' },
    ],
  },
  {
    exerciseId: 'db_rdl',
    name: 'Dumbbell Romanian Deadlift',
    aliases: ['DB RDL'],
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['erectors'],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Great for home users with no barbell.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs, short range.', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Heavier DBs, tempo.', typicalReps: '4 x 6–8' },
    ],
  },
  {
    exerciseId: 'kb_clean',
    name: 'Kettlebell Clean',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'HINGE',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['forearms', 'traps', 'core'],
    equipment: ['kettlebell'],
    space: 'OPEN_AREA',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'ASSISTANCE'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Dynamic hinge; pairs well with presses or squats.',
    tiers: [
      { tier: 'SILVER', description: 'Light single KB cleans.', typicalReps: '3 x 6–8 each' },
      { tier: 'GOLD', description: 'Moderate KB, continuous reps.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Double KB cleans or long EMOMs.', typicalReps: '10–15 per set' },
    ],
  },
  {
    exerciseId: 'kb_snatch',
    name: 'Kettlebell Snatch',
    aliases: [],
    category: 'SKILL',
    movementPattern: 'HINGE',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['shoulders', 'traps', 'core'],
    equipment: ['kettlebell'],
    space: 'OPEN_AREA',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Higher-skill hinge; keep for GOLD/BLACK.',
    tiers: [
      { tier: 'SILVER', description: 'KB high pulls instead of snatch.', typicalReps: '3 x 10 each' },
      { tier: 'GOLD', description: 'Light-moderate snatches.', typicalReps: '4 x 8–12 each' },
      { tier: 'BLACK', description: 'Heavier or long EMOM sets.', typicalReps: '10–15 each side' },
    ],
  },
  {
    exerciseId: 'kb_turkish_getup',
    name: 'Kettlebell Turkish Get-Up',
    aliases: ['TGU'],
    category: 'SKILL',
    movementPattern: 'FULL_BODY',
    primaryMuscles: ['shoulders', 'core', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lats'],
    equipment: ['kettlebell'],
    space: 'OPEN_AREA',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'ASSISTANCE', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE', 'FORGE'],
    indoorFriendly: true,
    notes: 'Great for stability and control.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight or shoe get-up.', typicalReps: '3 x 1–2 each' },
      { tier: 'GOLD', description: 'Light-moderate KB.', typicalReps: '3 x 2–3 each' },
      { tier: 'BLACK', description: 'Heavier KB or continuous flow.', typicalReps: '3 x 3–4 each' },
    ],
  },
  {
    exerciseId: 'sandbag_squat',
    name: 'Sandbag Squat',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'upper_back'],
    equipment: ['sandbag'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'ASSISTANCE'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'Hyrox-style loaded squats.',
    tiers: [
      { tier: 'SILVER', description: 'Light sandbag hugged.', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Moderate front-loaded bag.', typicalReps: '4 x 10–15' },
      { tier: 'BLACK', description: 'Heavier bag in circuits.', typicalReps: 'AMRAP 45–60s' },
    ],
  },
  {
    exerciseId: 'sandbag_lunge',
    name: 'Sandbag Walking Lunge',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'LUNGE',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['sandbag'],
    space: 'LANE_10M',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CAPAC1TY', 'CIRCUIT_X'],
    indoorFriendly: false,
    notes: 'Classic Hyrox station; long distance lunges.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight or light bag.', typicalReps: '2 x 20–30 steps' },
      { tier: 'GOLD', description: 'Moderate sandbag, steady pace.', typicalReps: '40–60 steps' },
      { tier: 'BLACK', description: 'Heavier bag, competition distance.', typicalReps: '80–100+ steps' },
    ],
  },
  {
    exerciseId: 'sandbag_carry',
    name: 'Sandbag Carry',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'CARRY',
    primaryMuscles: ['glutes', 'core', 'upper_back'],
    secondaryMuscles: ['grip'],
    equipment: ['sandbag'],
    space: 'LANE_10M',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CAPAC1TY', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Bear hug or shoulder carry; brutal core and lungs.',
    tiers: [
      { tier: 'SILVER', description: 'Light bag, short walks.', typicalReps: '3 x 20–30m' },
      { tier: 'GOLD', description: 'Moderate bag.', typicalReps: '3–4 x 30–40m' },
      { tier: 'BLACK', description: 'Heavy bag, long carries.', typicalReps: '4 x 40–60m' },
    ],
  },
  {
    exerciseId: 'run_400m',
    name: 'Run 400m',
    aliases: ['400m Run'],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads', 'hamstrings', 'glutes', 'calves'],
    secondaryMuscles: ['core'],
    equipment: [],
    space: 'RUN_ROUTE',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CAPAC1TY', 'ENGIN3'],
    indoorFriendly: false,
    notes: 'Track or outdoor loop.',
    tiers: [
      { tier: 'SILVER', description: 'Jog or power-walk.', typicalReps: '1–3 repeats' },
      { tier: 'GOLD', description: 'Steady run.', typicalReps: '3–6 repeats' },
      { tier: 'BLACK', description: 'Hard intervals.', typicalReps: '4–8 repeats' },
    ],
  },
  {
    exerciseId: 'run_1km',
    name: 'Run 1km',
    aliases: ['1000m Run'],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads', 'hamstrings', 'glutes', 'calves'],
    secondaryMuscles: ['core'],
    equipment: [],
    space: 'RUN_ROUTE',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CAPAC1TY'],
    indoorFriendly: false,
    notes: 'Hyrox style run interval.',
    tiers: [
      { tier: 'SILVER', description: 'Easy jog or walk-jog.', typicalReps: '1–2 x 1km' },
      { tier: 'GOLD', description: 'Steady run.', typicalReps: '2–4 x 1km' },
      { tier: 'BLACK', description: 'Hard threshold pace.', typicalReps: '3–5 x 1km' },
    ],
  },
  {
    exerciseId: 'shuttle_run_20m',
    name: '20m Shuttle Run',
    aliases: [],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads', 'calves', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: [],
    space: 'LANE_10M',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CIRCUIT_X', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Short accelerations; good in EMOMs.',
    tiers: [
      { tier: 'SILVER', description: 'Walk/jog shuttles.', typicalReps: '6–10 lengths' },
      { tier: 'GOLD', description: 'Run shuttles.', typicalReps: '10–20 lengths' },
      { tier: 'BLACK', description: 'Sprint shuttles.', typicalReps: '20–30+ lengths' },
    ],
  },
  {
    exerciseId: 'jump_rope_single',
    name: 'Single-Under Jump Rope',
    aliases: ['Skip Rope'],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['forearms', 'shoulders'],
    equipment: ['jump_rope'],
    space: 'OPEN_AREA',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING', 'WARMUP'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Great warmup or conditioning tool.',
    tiers: [
      { tier: 'SILVER', description: 'Short, easy bouts.', typicalReps: '30–60s' },
      { tier: 'GOLD', description: 'Longer sets.', typicalReps: '60–120s' },
      { tier: 'BLACK', description: 'High-speed or longer intervals.', typicalReps: '90–180s' },
    ],
  },
  {
    exerciseId: 'jump_rope_double',
    name: 'Double-Under Jump Rope',
    aliases: ['Double Unders'],
    category: 'SKILL',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['forearms', 'shoulders', 'core'],
    equipment: ['jump_rope'],
    space: 'OPEN_AREA',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Skillful plyometric conditioning.',
    tiers: [
      { tier: 'SILVER', description: 'Practice singles or low DUs.', typicalReps: '20–40 reps' },
      { tier: 'GOLD', description: 'Moderate DU sets.', typicalReps: '40–80 reps' },
      { tier: 'BLACK', description: 'Large unbroken sets.', typicalReps: '80–150 reps' },
    ],
  },
  {
    exerciseId: 'plank_front',
    name: 'Front Plank',
    aliases: ['Forearm Plank'],
    category: 'CORE',
    movementPattern: 'CORE_ANTI_EXTENSION',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['glutes', 'shoulders'],
    equipment: [],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'ASSISTANCE', 'FLOWSTATE'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Simple core brace drill.',
    tiers: [
      { tier: 'SILVER', description: 'Short holds.', typicalReps: '3 x 20–30s' },
      { tier: 'GOLD', description: 'Moderate holds.', typicalReps: '3 x 30–45s' },
      { tier: 'BLACK', description: 'Long or weighted holds.', typicalReps: '3 x 45–60s' },
    ],
  },
  {
    exerciseId: 'plank_side',
    name: 'Side Plank',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ROTATION',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['glutes', 'shoulders'],
    equipment: [],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'ASSISTANCE'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Anti-lateral-flexion control.',
    tiers: [
      { tier: 'SILVER', description: 'Knees bent.', typicalReps: '3 x 20–30s each' },
      { tier: 'GOLD', description: 'Full side plank.', typicalReps: '3 x 30–40s each' },
      { tier: 'BLACK', description: 'Top leg raised or loaded.', typicalReps: '3 x 40–60s each' },
    ],
  },
  {
    exerciseId: 'dead_bug',
    name: 'Dead Bug',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ANTI_EXTENSION',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors'],
    equipment: [],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Spine-friendly core pattern.',
    tiers: [
      { tier: 'SILVER', description: 'Short ROM.', typicalReps: '3 x 6–8 each' },
      { tier: 'GOLD', description: 'Full limbs extended.', typicalReps: '3 x 8–10 each' },
      { tier: 'BLACK', description: 'Slow tempo or band-resisted.', typicalReps: '3 x 10–12 each' },
    ],
  },
  {
    exerciseId: 'hollow_hold',
    name: 'Hollow Body Hold',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ANTI_EXTENSION',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors'],
    equipment: [],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Gymnastics-style core hold; used in REVL warmups.',
    tiers: [
      { tier: 'SILVER', description: 'Tucked hollow.', typicalReps: '3 x 20–30s' },
      { tier: 'GOLD', description: 'Full hollow.', typicalReps: '3 x 20–40s' },
      { tier: 'BLACK', description: 'Weighted or extended time.', typicalReps: '3 x 40–60s' },
    ],
  },
  {
    exerciseId: 'russian_twist',
    name: 'Russian Twist',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ROTATION',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['hip_flexors'],
    equipment: ['plate', 'medicine_ball'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['FINISHER'],
    suitableArchetypes: ['CIRCUIT_X', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Rotational core finisher.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight, feet down.', typicalReps: '3 x 20 total' },
      { tier: 'GOLD', description: 'Light load, feet up.', typicalReps: '3 x 30–40 total' },
      { tier: 'BLACK', description: 'Heavier load or long sets.', typicalReps: '3 x 40–60 total' },
    ],
  },
  {
    exerciseId: 'pallof_press',
    name: 'Pallof Press',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ROTATION',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['glutes'],
    equipment: ['cable', 'band'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'FLOWSTATE'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Anti-rotation drill.',
    tiers: [
      { tier: 'SILVER', description: 'Light band.', typicalReps: '3 x 10 each' },
      { tier: 'GOLD', description: 'Moderate resistance.', typicalReps: '3 x 12–15 each' },
      { tier: 'BLACK', description: 'Heavier or extended holds.', typicalReps: '3 x 15–20 each' },
    ],
  },
  {
    exerciseId: 'bear_crawl',
    name: 'Bear Crawl',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['shoulders', 'core'],
    secondaryMuscles: ['quads', 'hip_flexors'],
    equipment: [],
    space: 'LANE_5M',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'WARMUP'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Crawling pattern; stabilising and spicy.',
    tiers: [
      { tier: 'SILVER', description: 'Short, slow crawls.', typicalReps: '3 x 10m' },
      { tier: 'GOLD', description: 'Moderate distance.', typicalReps: '3–4 x 15–20m' },
      { tier: 'BLACK', description: 'Fast or long crawls.', typicalReps: '4 x 20–30m' },
    ],
  },
  {
    exerciseId: 'inchworm',
    name: 'Inchworm Walkout',
    aliases: [],
    category: 'MOBILITY',
    movementPattern: 'FULL_BODY',
    primaryMuscles: ['hamstrings', 'shoulders'],
    secondaryMuscles: ['core'],
    equipment: [],
    space: 'LANE_5M',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Dynamic hamstring + shoulder opener.',
    tiers: [
      { tier: 'SILVER', description: 'Short walkouts.', typicalReps: '2 x 6–8' },
      { tier: 'GOLD', description: 'Full walkouts + push-up optional.', typicalReps: '2–3 x 8–10' },
      { tier: 'BLACK', description: 'With push-ups or longer sets.', typicalReps: '3 x 10–12' },
    ],
  },
  {
    exerciseId: 'worlds_greatest_stretch',
    name: "World's Greatest Stretch",
    aliases: [],
    category: 'MOBILITY',
    movementPattern: 'BREATH_MOBILITY',
    primaryMuscles: ['hip_flexors', 'hamstrings'],
    secondaryMuscles: ['thoracic_spine'],
    equipment: [],
    space: 'OPEN_AREA',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Global mobility drill; appears often in warmups.',
    tiers: [
      { tier: 'SILVER', description: 'Short holds, supported.', typicalReps: '5 reps each side' },
      { tier: 'GOLD', description: 'Full range.', typicalReps: '6–8 reps each' },
      { tier: 'BLACK', description: 'Slow tempo and extended time.', typicalReps: '8–10 reps each' },
    ],
  },
  {
    exerciseId: 'cossack_squat',
    name: 'Cossack Squat',
    aliases: [],
    category: 'MOBILITY',
    movementPattern: 'SQUAT',
    primaryMuscles: ['adductors', 'quads'],
    secondaryMuscles: ['glutes'],
    equipment: [],
    space: 'OPEN_AREA',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Lateral squat mobility.',
    tiers: [
      { tier: 'SILVER', description: 'High hip, supported.', typicalReps: '2 x 8 each' },
      { tier: 'GOLD', description: 'Deeper range.', typicalReps: '3 x 8–10 each' },
      { tier: 'BLACK', description: 'Weighted or slower tempo.', typicalReps: '3 x 10–12 each' },
    ],
  },
  // Additional exercises from user
  {
    exerciseId: 'bb_back_squat',
    name: 'Barbell Back Squat',
    aliases: ['Back Squat', 'BB Back Squat'],
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['barbell', 'plates', 'rack'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['PRIMARY', 'ASSISTANCE'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Staple lower-body strength lift. Great for PR1ME waves and FORGE supersets. Contraindications: knee pain, low back pain.',
    tiers: [
      { tier: 'SILVER', description: 'Goblet squat or box squat with light barbell; focus on depth and control. RPE 6–7', typicalReps: '3–4 x 8–10' },
      { tier: 'GOLD', description: 'Full range back squat with moderate load. 60–75% 1RM', typicalReps: '4–5 x 5–8' },
      { tier: 'BLACK', description: 'Heavy back squat waves, top set plus back-off volume. 75–90% 1RM', typicalReps: '5–6 x 3–5' },
    ],
  },
  {
    exerciseId: 'bb_front_squat',
    name: 'Barbell Front Squat',
    aliases: ['Front Squat', 'BB Front Squat'],
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'upper_back'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['barbell', 'plates', 'rack'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['PRIMARY', 'ASSISTANCE'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'More upright torso; great for hybrid strength and posture.',
    tiers: [
      { tier: 'SILVER', description: 'Front squat to box or goblet front squat. Light–moderate, RPE 6', typicalReps: '3 x 6–8' },
      { tier: 'GOLD', description: 'Standard front squat with clean grip or straps. 65–80% 1RM', typicalReps: '4 x 4–6' },
      { tier: 'BLACK', description: 'Heavy front squat waves or EMOM doubles. 75–85% 1RM', typicalReps: '6 x 2–4' },
    ],
  },
  {
    exerciseId: 'bb_deadlift',
    name: 'Barbell Deadlift',
    aliases: ['Deadlift', 'Conventional Deadlift'],
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['erectors', 'lats', 'core'],
    equipment: ['barbell', 'plates'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['PRIMARY'],
    suitableArchetypes: ['PR1ME', 'FORGE'],
    indoorFriendly: true,
    notes: 'Key hinge pattern. Use more in PR1ME / heavy strength, less in high-fatigue conditioning. Contraindications: acute low back pain.',
    tiers: [
      { tier: 'SILVER', description: 'Kettlebell deadlift or trap-bar deadlift from blocks. RPE 6–7', typicalReps: '3 x 6–8' },
      { tier: 'GOLD', description: 'Standard deadlift, controlled eccentrics. 70–85% 1RM', typicalReps: '4–5 x 3–6' },
      { tier: 'BLACK', description: 'Heavy waves, singles/doubles with long rest. 80–90% 1RM (no grinding)', typicalReps: '6 x 1–3' },
    ],
  },
  {
    exerciseId: 'bb_hip_thrust',
    name: 'Barbell Hip Thrust',
    aliases: ['Hip Thrust', 'BB Hip Thrust'],
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['barbell', 'plates', 'bench'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['PRIMARY', 'ASSISTANCE'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'High glute activation with low spinal load.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight or banded hip thrust. Bodyweight / light band', typicalReps: '3–4 x 12–15' },
      { tier: 'GOLD', description: 'Standard barbell hip thrust. RPE 7–8', typicalReps: '4 x 8–12' },
      { tier: 'BLACK', description: 'Heavy barbell hip thrust with pause at top. Heavy, RPE 8–9', typicalReps: '5 x 6–8' },
    ],
  },
  {
    exerciseId: 'bb_rdl',
    name: 'Barbell Romanian Deadlift',
    aliases: ['RDL', 'Romanian Deadlift'],
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['erectors'],
    equipment: ['barbell', 'plates'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['ASSISTANCE', 'PRIMARY'],
    suitableArchetypes: ['PR1ME', 'FORGE'],
    indoorFriendly: true,
    notes: 'Great posterior chain builder; fits well as S2 block in PR1ME.',
    tiers: [
      { tier: 'SILVER', description: 'Dumbbell RDL from blocks or limited range. Light–moderate', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Full range barbell RDL. RPE 7–8', typicalReps: '4 x 6–10' },
      { tier: 'BLACK', description: 'Heavy RDL, slow eccentric. 70–80% conventional DL 1RM', typicalReps: '4–5 x 5–8' },
    ],
  },
  {
    exerciseId: 'bb_bench_press',
    name: 'Barbell Bench Press',
    aliases: ['Bench Press', 'BB Bench'],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['barbell', 'plates', 'bench'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['PRIMARY'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Primary upper-body strength marker; appears across PR1ME and FORGE templates.',
    tiers: [
      { tier: 'SILVER', description: 'Dumbbell floor press or push-up variations. Bodyweight or light DBs', typicalReps: '3–4 x 10–12' },
      { tier: 'GOLD', description: 'Standard bench with moderate load. 65–80% 1RM', typicalReps: '4–5 x 5–8' },
      { tier: 'BLACK', description: 'Heavy bench waves with pause reps. 75–88% 1RM', typicalReps: '5–6 x 3–5' },
    ],
  },
  {
    exerciseId: 'bb_strict_press',
    name: 'Barbell Strict Press',
    aliases: ['Overhead Press', 'BB OHP'],
    category: 'STRENGTH',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['delts'],
    secondaryMuscles: ['triceps', 'upper_chest', 'core'],
    equipment: ['barbell', 'plates', 'rack'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['PRIMARY', 'ASSISTANCE'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'High stability demand; great in upper PR1ME or FORGE supersets.',
    tiers: [
      { tier: 'SILVER', description: 'Seated dumbbell press. Light–moderate', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Standing barbell strict press. 60–75% 1RM', typicalReps: '4 x 5–8' },
      { tier: 'BLACK', description: 'Heavy strict press; can pair with push press. 70–85% 1RM', typicalReps: '5 x 3–5' },
    ],
  },
  {
    exerciseId: 'bb_push_press',
    name: 'Barbell Push Press',
    aliases: ['Push Press'],
    category: 'MIXED',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['delts', 'triceps'],
    secondaryMuscles: ['quads', 'glutes', 'core'],
    equipment: ['barbell', 'plates', 'rack'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['FORGE', 'ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Bridges strength and power; good for EMOM power work.',
    tiers: [
      { tier: 'SILVER', description: 'DB push press with light dumbbells. RPE 6–7', typicalReps: '3 x 8–10' },
      { tier: 'GOLD', description: 'BB push press moderate load. RPE 7–8', typicalReps: '4 x 5–8' },
      { tier: 'BLACK', description: 'Heavy triples in EMOM or wave loading. RPE 8–9', typicalReps: '6 x 3–4' },
    ],
  },
  {
    exerciseId: 'bb_bent_over_row',
    name: 'Barbell Bent-Over Row',
    aliases: ['BB Row', 'Bent Row'],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['lats', 'mid_back'],
    secondaryMuscles: ['rear_delts', 'biceps'],
    equipment: ['barbell', 'plates'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['ASSISTANCE', 'PRIMARY'],
    suitableArchetypes: ['FORGE', 'PR1ME'],
    indoorFriendly: true,
    notes: 'Key posture + pulling strength movement.',
    tiers: [
      { tier: 'SILVER', description: 'Chest-supported DB row. Light–moderate', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Standard hinged BB row. RPE 7–8', typicalReps: '4 x 6–10' },
      { tier: 'BLACK', description: 'Heavy Pendlay rows or strict bent rows. Heavy, RPE 8', typicalReps: '5 x 5–6' },
    ],
  },
  {
    exerciseId: 'db_goblet_squat',
    name: 'Dumbbell Goblet Squat',
    aliases: ['Goblet Squat'],
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbell', 'kettlebell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3', 'CIRCUIT_X', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Entry-level squat pattern; easy to teach.',
    tiers: [
      { tier: 'SILVER', description: 'Light goblet; tempo and depth focus. RPE 5–6', typicalReps: '3 x 10–15' },
      { tier: 'GOLD', description: 'Heavier goblet, can be in EMOM or AMRAP. RPE 7', typicalReps: '4 x 8–12' },
      { tier: 'BLACK', description: 'Heavy goblet or double-KB front squat. Challenging, near limit of front rack', typicalReps: '5 x 8–10' },
    ],
  },
  {
    exerciseId: 'kb_russian_swing',
    name: 'Kettlebell Russian Swing',
    aliases: ['KB Swing'],
    category: 'MIXED',
    movementPattern: 'HINGE',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lats', 'core', 'grip'],
    equipment: ['kettlebell'],
    space: 'OPEN_AREA',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'FINISHER'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'High power output hinge; staple in REVL-style circuits.',
    tiers: [
      { tier: 'SILVER', description: 'Light KB, chest height only, strict form. RPE 6', typicalReps: '10–15 reps or 30s on' },
      { tier: 'GOLD', description: 'Moderate KB, higher volume. RPE 7–8', typicalReps: '15–20 reps or 40s on' },
      { tier: 'BLACK', description: 'Heavy KB, aggressive hip drive, high volume EMOM. RPE 8–9', typicalReps: '20+ reps per set or 45–60s on' },
    ],
  },
  {
    exerciseId: 'kb_front_rack_lunge',
    name: 'Kettlebell Front Rack Lunge',
    aliases: ['KB Lunge'],
    category: 'MIXED',
    movementPattern: 'LUNGE',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['kettlebell'],
    space: 'LANE_5M',
    impactLevel: 'MEDIUM',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['FORGE', 'ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Unilateral strength and stability; brutal in longer sets.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight or goblet stationary lunge. RPE 6', typicalReps: '3 x 8–10 each leg' },
      { tier: 'GOLD', description: 'Walking KB front rack lunge. RPE 7–8', typicalReps: '4 x 10–12 steps' },
      { tier: 'BLACK', description: 'Double KB front rack lunge in EMOM or AMRAP. RPE 8–9', typicalReps: 'Heavy steps or 40s on' },
    ],
  },
  {
    exerciseId: 'push_up',
    name: 'Push-Up',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts', 'core'],
    equipment: [],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['FORGE', 'ENGIN3', 'CIRCUIT_X', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Bodyweight staple; easily scalable.',
    tiers: [
      { tier: 'SILVER', description: 'Incline push-ups on box or bench. RPE 5–6', typicalReps: '3 x 8–12' },
      { tier: 'GOLD', description: 'Full push-ups from floor. Bodyweight, RPE 7–8', typicalReps: '3–4 x 10–20' },
      { tier: 'BLACK', description: 'Deficit or weighted push-ups, high volume sets. RPE 8–9', typicalReps: '4 x 15–25' },
    ],
  },
  {
    exerciseId: 'pull_up',
    name: 'Pull-Up',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'mid_back'],
    equipment: ['rig'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['PRIMARY', 'ASSISTANCE'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Classic vertical pull; used heavily in REVL upper days.',
    tiers: [
      { tier: 'SILVER', description: 'Band-assisted pull-up or ring row. Bodyweight with assistance', typicalReps: '3 x 6–10' },
      { tier: 'GOLD', description: 'Strict pull-ups. Bodyweight', typicalReps: '4 x 4–8' },
      { tier: 'BLACK', description: 'Weighted pull-ups or high-volume sets. Additional load, RPE 8', typicalReps: '5 x 3–6 or EMOM reps' },
    ],
  },
  {
    exerciseId: 'ttb',
    name: 'Toes to Bar',
    aliases: ['TTB'],
    category: 'SKILL',
    movementPattern: 'FULL_BODY',
    primaryMuscles: ['abs', 'hip_flexors'],
    secondaryMuscles: ['grip', 'lats'],
    equipment: ['rig'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'FINISHER'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'Gymnastics core move, appears in REVL as TTB/TTK combos.',
    tiers: [
      { tier: 'SILVER', description: 'Hanging knee raises. Bodyweight', typicalReps: '3 x 8–12' },
      { tier: 'GOLD', description: 'Strict or kipping TTB as able. Bodyweight', typicalReps: '3–4 x 6–10' },
      { tier: 'BLACK', description: 'High-volume kipping TTB in EMOM/AMRAP. RPE 8–9', typicalReps: '10–15+ per set' },
    ],
  },
  {
    exerciseId: 'burpee',
    name: 'Burpee',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'FULL_BODY',
    primaryMuscles: ['chest', 'shoulders', 'quads'],
    secondaryMuscles: ['core', 'hip_flexors'],
    equipment: [],
    space: 'OPEN_AREA',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING', 'FINISHER'],
    suitableArchetypes: ['CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'High impact, full-body; used a lot for finishers. Contraindications: wrist pain, shoulder pain, low back pain.',
    tiers: [
      { tier: 'SILVER', description: 'Step-back burpee, no jump. RPE 6–7', typicalReps: '20–40 in a session' },
      { tier: 'GOLD', description: 'Standard burpee with small jump. RPE 7–8', typicalReps: '40–80 per session' },
      { tier: 'BLACK', description: 'Burpee broad jumps or target burpees. RPE 8–9', typicalReps: 'High volume or EMOM sets' },
    ],
  },
  {
    exerciseId: 'box_jump',
    name: 'Box Jump',
    aliases: [],
    category: 'SKILL',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['core'],
    equipment: ['plyo_box'],
    space: 'OPEN_AREA',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING', 'ASSISTANCE'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Power plyometric; careful with fatigue. Contraindications: knee pain, ankle pain.',
    tiers: [
      { tier: 'SILVER', description: 'Low box step-ups or step-up + knee drive. Low height', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Standard box jumps, stick landings. RPE 7', typicalReps: '3–4 x 6–10' },
      { tier: 'BLACK', description: 'Higher box or repeat jumps in conditioning. RPE 8–9', typicalReps: '10–20 per set' },
    ],
  },
  {
    exerciseId: 'row_erg',
    name: 'RowErg',
    aliases: ['Rowing Machine', 'Concept2 Row'],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads', 'glutes', 'lats'],
    secondaryMuscles: ['hamstrings', 'biceps', 'core'],
    equipment: ['rower'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['CONDITIONING', 'FINISHER'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'Staple engine piece; easy to dose calories or meters.',
    tiers: [
      { tier: 'SILVER', description: 'Easy aerobic rows. Zone 2 or 10–14 cal per interval. RPE 5–6', typicalReps: 'Zone 2 or 10–14 cal per interval' },
      { tier: 'GOLD', description: 'Mixed pace intervals. RPE 7–8', typicalReps: '12–16 cal or 250–400m repeats' },
      { tier: 'BLACK', description: 'Hard intervals or long threshold pieces. RPE 8–9', typicalReps: '20+ cal intervals or 500m repeats' },
    ],
  },
  {
    exerciseId: 'ski_erg',
    name: 'SkiErg',
    aliases: ['Ski Erg'],
    category: 'ENGINE',
    movementPattern: 'VERTICAL_PULL',
    primaryMuscles: ['lats', 'triceps'],
    secondaryMuscles: ['core', 'glutes'],
    equipment: ['ski_erg'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['ENGIN3', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'Hyrox staple station; great for upper-body engine.',
    tiers: [
      { tier: 'SILVER', description: 'Short easy intervals. RPE 5–6', typicalReps: '8–12 cal' },
      { tier: 'GOLD', description: 'Moderate intervals. RPE 7–8', typicalReps: '12–16 cal' },
      { tier: 'BLACK', description: 'High-cal or high-power sets. RPE 8–9', typicalReps: '18–25 cal or 300–500m' },
    ],
  },
  {
    exerciseId: 'bike_erg',
    name: 'Assault / Echo Bike',
    aliases: ['Air Bike', 'BikeErg (fan)'],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves', 'arms'],
    equipment: ['air_bike'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['CONDITIONING', 'FINISHER'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'Brutal but safe; perfect for finishers and capacity days.',
    tiers: [
      { tier: 'SILVER', description: 'Easy spins or short intervals. RPE 5–6', typicalReps: '6–10 cal' },
      { tier: 'GOLD', description: 'Moderate intensity intervals. RPE 7–8', typicalReps: '10–15 cal' },
      { tier: 'BLACK', description: 'Hard sprints or long sets. RPE 9', typicalReps: '15–25 cal or 30–60s all-out' },
    ],
  },
  {
    exerciseId: 'sled_push',
    name: 'Sled Push',
    aliases: ['Prowler Push'],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['sled', 'plates'],
    space: 'LANE_10M',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'PRIMARY'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: false,
    notes: 'Core Hyrox station; needs lane – filter out for home users.',
    tiers: [
      { tier: 'SILVER', description: 'Light sled, marching pace. Bodyweight-ish', typicalReps: '2–4 x 10–20m' },
      { tier: 'GOLD', description: 'Moderate to heavy push intervals. Bodyweight+', typicalReps: '4–6 x 10–25m' },
      { tier: 'BLACK', description: 'Heavy competition-style pushes. Very heavy, RPE 9', typicalReps: '6–10 efforts of 15–25m' },
    ],
  },
  {
    exerciseId: 'sled_pull',
    name: 'Sled Pull (Backward)',
    aliases: [],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['sled', 'rope', 'harness', 'plates'],
    space: 'LANE_10M',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['ENGIN3', 'CAPAC1TY'],
    indoorFriendly: false,
    notes: 'Hyrox pull station; great quad pump.',
    tiers: [
      { tier: 'SILVER', description: 'Light sled backward walks. Light', typicalReps: '2–4 x 10–20m' },
      { tier: 'GOLD', description: 'Moderate sled pulls with rope/harness. Moderate-heavy', typicalReps: '4–6 x 15–25m' },
      { tier: 'BLACK', description: 'Heavy competition-style pulls. Very heavy, RPE 9', typicalReps: '6–8 x 20–25m' },
    ],
  },
  {
    exerciseId: 'farmer_carry',
    name: 'Farmer Carry',
    aliases: ['Farmer Walk'],
    category: 'MIXED',
    movementPattern: 'CARRY',
    primaryMuscles: ['grip', 'traps'],
    secondaryMuscles: ['core', 'glutes'],
    equipment: ['dumbbell', 'kettlebell', 'farmer_handles'],
    space: 'LANE_10M',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'ASSISTANCE'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'Hyrox farmer carry variation; easy to scale length/load.',
    tiers: [
      { tier: 'SILVER', description: 'Light DB carries. RPE 6', typicalReps: '3 x 20m' },
      { tier: 'GOLD', description: 'Heavier KB or DB carries. RPE 7–8', typicalReps: '4 x 20–40m' },
      { tier: 'BLACK', description: 'Very heavy farmers or long-distance carries. RPE 8–9', typicalReps: '40–80m efforts' },
    ],
  },
  {
    exerciseId: 'wall_ball',
    name: 'Wall Ball Shot',
    aliases: ['Wall Ball'],
    category: 'ENGINE',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes', 'shoulders'],
    secondaryMuscles: ['core'],
    equipment: ['wall_ball', 'target_wall'],
    space: 'OPEN_AREA',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'Hyrox final station; very scalable by ball weight.',
    tiers: [
      { tier: 'SILVER', description: 'Light ball, lower target or goblet squat + press. RPE 6–7', typicalReps: '10–15 per set' },
      { tier: 'GOLD', description: 'Standard ball weight and target height. RPE 7–8', typicalReps: '15–25 per set' },
      { tier: 'BLACK', description: 'High-rep sets or heavier ball. RPE 8–9', typicalReps: '25–40 per set' },
    ],
  },
];

async function main() {
  console.log('🌱 Seeding exercises database...');

  for (const exerciseData of exercisesData) {
    const { tiers, ...exercise } = exerciseData;

    // Upsert exercise (without tiers) - cast enums properly
    const exerciseRecord = await prisma.exercise.upsert({
      where: { exerciseId: exercise.exerciseId },
      update: {
        ...exercise,
        category: exercise.category as any,
        movementPattern: exercise.movementPattern as any,
        space: exercise.space as any,
        impactLevel: exercise.impactLevel as any,
        typicalUse: exercise.typicalUse as any,
        suitableArchetypes: exercise.suitableArchetypes as any,
      },
      create: {
        ...exercise,
        category: exercise.category as any,
        movementPattern: exercise.movementPattern as any,
        space: exercise.space as any,
        impactLevel: exercise.impactLevel as any,
        typicalUse: exercise.typicalUse as any,
        suitableArchetypes: exercise.suitableArchetypes as any,
      },
    });

    // Delete existing tiers
    await prisma.exerciseTier.deleteMany({
      where: { exerciseId: exerciseRecord.id },
    });

    // Create new tiers
    if (tiers && tiers.length > 0) {
      await prisma.exerciseTier.createMany({
        data: tiers.map((tier) => ({
          exerciseId: exerciseRecord.id,
          tier: tier.tier as any,
          description: tier.description,
          typicalReps: tier.typicalReps,
        })),
      });
    }
  }

  console.log(`✅ Seeded ${exercisesData.length} exercises`);
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

