import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const exercisesData = [
  {
    exerciseId: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    aliases: ['DB Bench'],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['dumbbell', 'bench'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['PRIMARY', 'ASSISTANCE'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'More ROM and unilateral stability vs barbell.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs, focus on tempo.', typicalReps: '3 x 10–15' },
      { tier: 'GOLD', description: 'Moderate DBs, strength focus.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Heavy DBs or slight incline.', typicalReps: '4–5 x 6–8' },
    ],
  },
  {
    exerciseId: 'db_incline_bench',
    name: 'Incline Dumbbell Bench Press',
    aliases: ['Incline DB Bench'],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['upper_chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['dumbbell', 'bench'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE'],
    suitableArchetypes: ['FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Targets upper chest and shoulders.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs.', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Heavy DBs.', typicalReps: '4 x 6–8' },
    ],
  },
  {
    exerciseId: 'db_floor_press',
    name: 'Dumbbell Floor Press',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PUSH',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'PRIMARY'],
    suitableArchetypes: ['PR1ME', 'FORGE'],
    indoorFriendly: true,
    notes: 'Great for shoulders; limited ROM.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs.', typicalReps: '3 x 12–15' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Heavy DBs.', typicalReps: '4 x 6–8' },
    ],
  },
  {
    exerciseId: 'db_row',
    name: 'Single-Arm Dumbbell Row',
    aliases: ['DB Row'],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['lats', 'mid_back'],
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell', 'bench'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE'],
    suitableArchetypes: ['FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Unilateral back builder; easy for all levels.',
    tiers: [
      { tier: 'SILVER', description: 'Light DB, controlled.', typicalReps: '3 x 12 each' },
      { tier: 'GOLD', description: 'Moderate load.', typicalReps: '4 x 8–10 each' },
      { tier: 'BLACK', description: 'Heavy DB in EMOM or superset.', typicalReps: '4 x 6–8 each' },
    ],
  },
  {
    exerciseId: 'db_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['lateral_delts'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'FINISHER'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Shoulder isolation; great pump work.',
    tiers: [
      { tier: 'SILVER', description: 'Very light DBs.', typicalReps: '3 x 15–20' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '3–4 x 10–15' },
      { tier: 'BLACK', description: 'Heavier with partials or drop sets.', typicalReps: '4 x 12–20' },
    ],
  },
  {
    exerciseId: 'db_bicep_curl',
    name: 'Dumbbell Biceps Curl',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'HORIZONTAL_PULL',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'FINISHER'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Simple arm work; good for supersets.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs.', typicalReps: '3 x 12–15' },
      { tier: 'GOLD', description: 'Moderate load.', typicalReps: '3–4 x 8–12' },
      { tier: 'BLACK', description: 'Heavier or tempo curls.', typicalReps: '4 x 8–10' },
    ],
  },
  {
    exerciseId: 'db_tricep_extension',
    name: 'Dumbbell Triceps Extension',
    aliases: ['Overhead Triceps Extension'],
    category: 'STRENGTH',
    movementPattern: 'VERTICAL_PUSH',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'FINISHER'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Lockout strength; single or two-hand.',
    tiers: [
      { tier: 'SILVER', description: 'Light DB, seated.', typicalReps: '3 x 12–15' },
      { tier: 'GOLD', description: 'Moderate load.', typicalReps: '3–4 x 10–12' },
      { tier: 'BLACK', description: 'Heavier, higher volume.', typicalReps: '4 x 8–10' },
    ],
  },
  {
    exerciseId: 'db_step_up',
    name: 'Dumbbell Step-Up',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['dumbbell', 'plyo_box'],
    space: 'OPEN_AREA',
    impactLevel: 'MEDIUM',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['FORGE', 'ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Unilateral leg strength and balance.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight or low box.', typicalReps: '3 x 8–10 each' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 10–12 steps' },
      { tier: 'BLACK', description: 'Heavier DBs or higher box.', typicalReps: '4 x 12–15 steps' },
    ],
  },
  {
    exerciseId: 'db_rev_lunge',
    name: 'Dumbbell Reverse Lunge',
    aliases: [],
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['dumbbell'],
    space: 'LANE_5M',
    impactLevel: 'MEDIUM',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Knee friendly unilateral pattern.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight reverse lunges.', typicalReps: '3 x 8–10 each' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 8–12 each' },
      { tier: 'BLACK', description: 'Heavier DBs or front rack.', typicalReps: '4 x 10–12 each' },
    ],
  },
  {
    exerciseId: 'db_rdl',
    name: 'Dumbbell Romanian Deadlift',
    aliases: ['DB RDL'],
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['erectors'],
    equipment: ['dumbbell'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['PR1ME', 'FORGE', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Great for home users with no barbell.',
    tiers: [
      { tier: 'SILVER', description: 'Light DBs, short range.', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Moderate DBs.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Heavier DBs, tempo.', typicalReps: '4 x 6–8' },
    ],
  },
  {
    exerciseId: 'kb_clean',
    name: 'Kettlebell Clean',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'HINGE',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['forearms', 'traps', 'core'],
    equipment: ['kettlebell'],
    space: 'OPEN_AREA',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'ASSISTANCE'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Dynamic hinge; pairs well with presses or squats.',
    tiers: [
      { tier: 'SILVER', description: 'Light single KB cleans.', typicalReps: '3 x 6–8 each' },
      { tier: 'GOLD', description: 'Moderate KB, continuous reps.', typicalReps: '4 x 8–10' },
      { tier: 'BLACK', description: 'Double KB cleans or long EMOMs.', typicalReps: '10–15 per set' },
    ],
  },
  {
    exerciseId: 'kb_snatch',
    name: 'Kettlebell Snatch',
    aliases: [],
    category: 'SKILL',
    movementPattern: 'HINGE',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['shoulders', 'traps', 'core'],
    equipment: ['kettlebell'],
    space: 'OPEN_AREA',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Higher-skill hinge; keep for GOLD/BLACK.',
    tiers: [
      { tier: 'SILVER', description: 'KB high pulls instead of snatch.', typicalReps: '3 x 10 each' },
      { tier: 'GOLD', description: 'Light-moderate snatches.', typicalReps: '4 x 8–12 each' },
      { tier: 'BLACK', description: 'Heavier or long EMOM sets.', typicalReps: '10–15 each side' },
    ],
  },
  {
    exerciseId: 'kb_turkish_getup',
    name: 'Kettlebell Turkish Get-Up',
    aliases: ['TGU'],
    category: 'SKILL',
    movementPattern: 'FULL_BODY',
    primaryMuscles: ['shoulders', 'core', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lats'],
    equipment: ['kettlebell'],
    space: 'OPEN_AREA',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'ASSISTANCE', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE', 'FORGE'],
    indoorFriendly: true,
    notes: 'Great for stability and control.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight or shoe get-up.', typicalReps: '3 x 1–2 each' },
      { tier: 'GOLD', description: 'Light-moderate KB.', typicalReps: '3 x 2–3 each' },
      { tier: 'BLACK', description: 'Heavier KB or continuous flow.', typicalReps: '3 x 3–4 each' },
    ],
  },
  {
    exerciseId: 'sandbag_squat',
    name: 'Sandbag Squat',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'SQUAT',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'upper_back'],
    equipment: ['sandbag'],
    space: 'SPOT',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'ASSISTANCE'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'CAPAC1TY'],
    indoorFriendly: true,
    notes: 'Hyrox-style loaded squats.',
    tiers: [
      { tier: 'SILVER', description: 'Light sandbag hugged.', typicalReps: '3 x 10–12' },
      { tier: 'GOLD', description: 'Moderate front-loaded bag.', typicalReps: '4 x 10–15' },
      { tier: 'BLACK', description: 'Heavier bag in circuits.', typicalReps: 'AMRAP 45–60s' },
    ],
  },
  {
    exerciseId: 'sandbag_lunge',
    name: 'Sandbag Walking Lunge',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'LUNGE',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['sandbag'],
    space: 'LANE_10M',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CAPAC1TY', 'CIRCUIT_X'],
    indoorFriendly: false,
    notes: 'Classic Hyrox station; long distance lunges.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight or light bag.', typicalReps: '2 x 20–30 steps' },
      { tier: 'GOLD', description: 'Moderate sandbag, steady pace.', typicalReps: '40–60 steps' },
      { tier: 'BLACK', description: 'Heavier bag, competition distance.', typicalReps: '80–100+ steps' },
    ],
  },
  {
    exerciseId: 'sandbag_carry',
    name: 'Sandbag Carry',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'CARRY',
    primaryMuscles: ['glutes', 'core', 'upper_back'],
    secondaryMuscles: ['grip'],
    equipment: ['sandbag'],
    space: 'LANE_10M',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CAPAC1TY', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Bear hug or shoulder carry; brutal core and lungs.',
    tiers: [
      { tier: 'SILVER', description: 'Light bag, short walks.', typicalReps: '3 x 20–30m' },
      { tier: 'GOLD', description: 'Moderate bag.', typicalReps: '3–4 x 30–40m' },
      { tier: 'BLACK', description: 'Heavy bag, long carries.', typicalReps: '4 x 40–60m' },
    ],
  },
  {
    exerciseId: 'run_400m',
    name: 'Run 400m',
    aliases: ['400m Run'],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads', 'hamstrings', 'glutes', 'calves'],
    secondaryMuscles: ['core'],
    equipment: [],
    space: 'RUN_ROUTE',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CAPAC1TY', 'ENGIN3'],
    indoorFriendly: false,
    notes: 'Track or outdoor loop.',
    tiers: [
      { tier: 'SILVER', description: 'Jog or power-walk.', typicalReps: '1–3 repeats' },
      { tier: 'GOLD', description: 'Steady run.', typicalReps: '3–6 repeats' },
      { tier: 'BLACK', description: 'Hard intervals.', typicalReps: '4–8 repeats' },
    ],
  },
  {
    exerciseId: 'run_1km',
    name: 'Run 1km',
    aliases: ['1000m Run'],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads', 'hamstrings', 'glutes', 'calves'],
    secondaryMuscles: ['core'],
    equipment: [],
    space: 'RUN_ROUTE',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CAPAC1TY'],
    indoorFriendly: false,
    notes: 'Hyrox style run interval.',
    tiers: [
      { tier: 'SILVER', description: 'Easy jog or walk-jog.', typicalReps: '1–2 x 1km' },
      { tier: 'GOLD', description: 'Steady run.', typicalReps: '2–4 x 1km' },
      { tier: 'BLACK', description: 'Hard threshold pace.', typicalReps: '3–5 x 1km' },
    ],
  },
  {
    exerciseId: 'shuttle_run_20m',
    name: '20m Shuttle Run',
    aliases: [],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['quads', 'calves', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: [],
    space: 'LANE_10M',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['CIRCUIT_X', 'ENGIN3'],
    indoorFriendly: true,
    notes: 'Short accelerations; good in EMOMs.',
    tiers: [
      { tier: 'SILVER', description: 'Walk/jog shuttles.', typicalReps: '6–10 lengths' },
      { tier: 'GOLD', description: 'Run shuttles.', typicalReps: '10–20 lengths' },
      { tier: 'BLACK', description: 'Sprint shuttles.', typicalReps: '20–30+ lengths' },
    ],
  },
  {
    exerciseId: 'jump_rope_single',
    name: 'Single-Under Jump Rope',
    aliases: ['Skip Rope'],
    category: 'ENGINE',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['forearms', 'shoulders'],
    equipment: ['jump_rope'],
    space: 'OPEN_AREA',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING', 'WARMUP'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Great warmup or conditioning tool.',
    tiers: [
      { tier: 'SILVER', description: 'Short, easy bouts.', typicalReps: '30–60s' },
      { tier: 'GOLD', description: 'Longer sets.', typicalReps: '60–120s' },
      { tier: 'BLACK', description: 'High-speed or longer intervals.', typicalReps: '90–180s' },
    ],
  },
  {
    exerciseId: 'jump_rope_double',
    name: 'Double-Under Jump Rope',
    aliases: ['Double Unders'],
    category: 'SKILL',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['forearms', 'shoulders', 'core'],
    equipment: ['jump_rope'],
    space: 'OPEN_AREA',
    impactLevel: 'HIGH',
    typicalUse: ['CONDITIONING'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X'],
    indoorFriendly: true,
    notes: 'Skillful plyometric conditioning.',
    tiers: [
      { tier: 'SILVER', description: 'Practice singles or low DUs.', typicalReps: '20–40 reps' },
      { tier: 'GOLD', description: 'Moderate DU sets.', typicalReps: '40–80 reps' },
      { tier: 'BLACK', description: 'Large unbroken sets.', typicalReps: '80–150 reps' },
    ],
  },
  {
    exerciseId: 'plank_front',
    name: 'Front Plank',
    aliases: ['Forearm Plank'],
    category: 'CORE',
    movementPattern: 'CORE_ANTI_EXTENSION',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['glutes', 'shoulders'],
    equipment: [],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'ASSISTANCE', 'FLOWSTATE'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Simple core brace drill.',
    tiers: [
      { tier: 'SILVER', description: 'Short holds.', typicalReps: '3 x 20–30s' },
      { tier: 'GOLD', description: 'Moderate holds.', typicalReps: '3 x 30–45s' },
      { tier: 'BLACK', description: 'Long or weighted holds.', typicalReps: '3 x 45–60s' },
    ],
  },
  {
    exerciseId: 'plank_side',
    name: 'Side Plank',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ROTATION',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['glutes', 'shoulders'],
    equipment: [],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'ASSISTANCE'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Anti-lateral-flexion control.',
    tiers: [
      { tier: 'SILVER', description: 'Knees bent.', typicalReps: '3 x 20–30s each' },
      { tier: 'GOLD', description: 'Full side plank.', typicalReps: '3 x 30–40s each' },
      { tier: 'BLACK', description: 'Top leg raised or loaded.', typicalReps: '3 x 40–60s each' },
    ],
  },
  {
    exerciseId: 'dead_bug',
    name: 'Dead Bug',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ANTI_EXTENSION',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors'],
    equipment: [],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Spine-friendly core pattern.',
    tiers: [
      { tier: 'SILVER', description: 'Short ROM.', typicalReps: '3 x 6–8 each' },
      { tier: 'GOLD', description: 'Full limbs extended.', typicalReps: '3 x 8–10 each' },
      { tier: 'BLACK', description: 'Slow tempo or band-resisted.', typicalReps: '3 x 10–12 each' },
    ],
  },
  {
    exerciseId: 'hollow_hold',
    name: 'Hollow Body Hold',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ANTI_EXTENSION',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors'],
    equipment: [],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'CONDITIONING'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Gymnastics-style core hold; used in REVL warmups.',
    tiers: [
      { tier: 'SILVER', description: 'Tucked hollow.', typicalReps: '3 x 20–30s' },
      { tier: 'GOLD', description: 'Full hollow.', typicalReps: '3 x 20–40s' },
      { tier: 'BLACK', description: 'Weighted or extended time.', typicalReps: '3 x 40–60s' },
    ],
  },
  {
    exerciseId: 'russian_twist',
    name: 'Russian Twist',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ROTATION',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['hip_flexors'],
    equipment: ['plate', 'medicine_ball'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['FINISHER'],
    suitableArchetypes: ['CIRCUIT_X', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Rotational core finisher.',
    tiers: [
      { tier: 'SILVER', description: 'Bodyweight, feet down.', typicalReps: '3 x 20 total' },
      { tier: 'GOLD', description: 'Light load, feet up.', typicalReps: '3 x 30–40 total' },
      { tier: 'BLACK', description: 'Heavier load or long sets.', typicalReps: '3 x 40–60 total' },
    ],
  },
  {
    exerciseId: 'pallof_press',
    name: 'Pallof Press',
    aliases: [],
    category: 'CORE',
    movementPattern: 'CORE_ROTATION',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['glutes'],
    equipment: ['cable', 'band'],
    space: 'SPOT',
    impactLevel: 'LOW',
    typicalUse: ['ASSISTANCE', 'FLOWSTATE'],
    suitableArchetypes: ['FORGE', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Anti-rotation drill.',
    tiers: [
      { tier: 'SILVER', description: 'Light band.', typicalReps: '3 x 10 each' },
      { tier: 'GOLD', description: 'Moderate resistance.', typicalReps: '3 x 12–15 each' },
      { tier: 'BLACK', description: 'Heavier or extended holds.', typicalReps: '3 x 15–20 each' },
    ],
  },
  {
    exerciseId: 'bear_crawl',
    name: 'Bear Crawl',
    aliases: [],
    category: 'MIXED',
    movementPattern: 'LOC0MOTION',
    primaryMuscles: ['shoulders', 'core'],
    secondaryMuscles: ['quads', 'hip_flexors'],
    equipment: [],
    space: 'LANE_5M',
    impactLevel: 'MEDIUM',
    typicalUse: ['CONDITIONING', 'WARMUP'],
    suitableArchetypes: ['ENGIN3', 'CIRCUIT_X', 'FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Crawling pattern; stabilising and spicy.',
    tiers: [
      { tier: 'SILVER', description: 'Short, slow crawls.', typicalReps: '3 x 10m' },
      { tier: 'GOLD', description: 'Moderate distance.', typicalReps: '3–4 x 15–20m' },
      { tier: 'BLACK', description: 'Fast or long crawls.', typicalReps: '4 x 20–30m' },
    ],
  },
  {
    exerciseId: 'inchworm',
    name: 'Inchworm Walkout',
    aliases: [],
    category: 'MOBILITY',
    movementPattern: 'FULL_BODY',
    primaryMuscles: ['hamstrings', 'shoulders'],
    secondaryMuscles: ['core'],
    equipment: [],
    space: 'LANE_5M',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Dynamic hamstring + shoulder opener.',
    tiers: [
      { tier: 'SILVER', description: 'Short walkouts.', typicalReps: '2 x 6–8' },
      { tier: 'GOLD', description: 'Full walkouts + push-up optional.', typicalReps: '2–3 x 8–10' },
      { tier: 'BLACK', description: 'With push-ups or longer sets.', typicalReps: '3 x 10–12' },
    ],
  },
  {
    exerciseId: 'worlds_greatest_stretch',
    name: "World's Greatest Stretch",
    aliases: [],
    category: 'MOBILITY',
    movementPattern: 'BREATH_MOBILITY',
    primaryMuscles: ['hip_flexors', 'hamstrings'],
    secondaryMuscles: ['thoracic_spine'],
    equipment: [],
    space: 'OPEN_AREA',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Global mobility drill; appears often in warmups.',
    tiers: [
      { tier: 'SILVER', description: 'Short holds, supported.', typicalReps: '5 reps each side' },
      { tier: 'GOLD', description: 'Full range.', typicalReps: '6–8 reps each' },
      { tier: 'BLACK', description: 'Slow tempo and extended time.', typicalReps: '8–10 reps each' },
    ],
  },
  {
    exerciseId: 'cossack_squat',
    name: 'Cossack Squat',
    aliases: [],
    category: 'MOBILITY',
    movementPattern: 'SQUAT',
    primaryMuscles: ['adductors', 'quads'],
    secondaryMuscles: ['glutes'],
    equipment: [],
    space: 'OPEN_AREA',
    impactLevel: 'LOW',
    typicalUse: ['WARMUP', 'FLOWSTATE'],
    suitableArchetypes: ['FLOWSTATE'],
    indoorFriendly: true,
    notes: 'Lateral squat mobility.',
    tiers: [
      { tier: 'SILVER', description: 'High hip, supported.', typicalReps: '2 x 8 each' },
      { tier: 'GOLD', description: 'Deeper range.', typicalReps: '3 x 8–10 each' },
      { tier: 'BLACK', description: 'Weighted or slower tempo.', typicalReps: '3 x 10–12 each' },
    ],
  },
];

async function main() {
  console.log('🌱 Seeding exercises database...');

  for (const exerciseData of exercisesData) {
    const { tiers, ...exercise } = exerciseData;

    // Upsert exercise (without tiers) - cast enums properly
    const exerciseRecord = await prisma.exercise.upsert({
      where: { exerciseId: exercise.exerciseId },
      update: {
        ...exercise,
        category: exercise.category as any,
        movementPattern: exercise.movementPattern as any,
        space: exercise.space as any,
        impactLevel: exercise.impactLevel as any,
        typicalUse: exercise.typicalUse as any,
        suitableArchetypes: exercise.suitableArchetypes as any,
      },
      create: {
        ...exercise,
        category: exercise.category as any,
        movementPattern: exercise.movementPattern as any,
        space: exercise.space as any,
        impactLevel: exercise.impactLevel as any,
        typicalUse: exercise.typicalUse as any,
        suitableArchetypes: exercise.suitableArchetypes as any,
      },
    });

    // Delete existing tiers
    await prisma.exerciseTier.deleteMany({
      where: { exerciseId: exerciseRecord.id },
    });

    // Create new tiers
    if (tiers && tiers.length > 0) {
      await prisma.exerciseTier.createMany({
        data: tiers.map((tier) => ({
          exerciseId: exerciseRecord.id,
          tier: tier.tier as any,
          description: tier.description,
          typicalReps: tier.typicalReps,
        })),
      });
    }
  }

  console.log(`✅ Seeded ${exercisesData.length} exercises`);
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

